import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import Notifications from "./components/Notifications";
import NotificationPopup from "./components/NotificationPopup";
import PrivacyPolicyLink from "./components/PrivacyPolicyLink";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <div className="drawer drawer-end ">
                        <input
                            id="my-drawer-4"
                            type="checkbox"
                            className="drawer-toggle"
                        />
                        <div className="drawer-content relative">
                            <Navbar />
                            {children}
                            <NotificationPopup />
                            <PrivacyPolicyLink />
                        </div>
                        <div className="drawer-side z-[1000]">
                            <label
                                htmlFor="my-drawer-4"
                                aria-label="close sidebar"
                                className="drawer-overlay"
                            ></label>
                            <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
                                <Notifications />
                            </ul>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
